// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetApiPaymentData, GetApiPaymentResponses, GetApiPaymentErrors, PostApiPaymentData, PostApiPaymentResponses, PostApiPaymentErrors, DeleteApiPaymentByPaymentIdData, DeleteApiPaymentByPaymentIdResponses, DeleteApiPaymentByPaymentIdErrors, GetApiPaymentByPaymentIdData, GetApiPaymentByPaymentIdResponses, GetApiPaymentByPaymentIdErrors, PostApiPaymentByPaymentIdRefundData, PostApiPaymentByPaymentIdRefundResponses, PostApiPaymentByPaymentIdRefundErrors, GetApiPaymentHealthData, GetApiPaymentHealthResponses, GetApiPaymentProvidersData, GetApiPaymentProvidersResponses, GetApiPaymentProvidersByProviderHealthData, GetApiPaymentProvidersByProviderHealthResponses, GetApiPaymentProvidersByProviderHealthErrors, GetApiKeysData, GetApiKeysResponses, GetApiKeysErrors, PostApiKeysGenerateData, PostApiKeysGenerateResponses, PostApiKeysGenerateErrors, PostApiKeysRotateData, PostApiKeysRotateResponses, PostApiKeysRotateErrors, DeleteApiKeysRevokeData, DeleteApiKeysRevokeResponses, DeleteApiKeysRevokeErrors, GetApiWebhooksData, GetApiWebhooksResponses, GetApiWebhooksErrors, PostApiWebhooksOrangeData, PostApiWebhooksOrangeResponses, PostApiWebhooksOrangeErrors, PostApiWebhooksByIdReplayData, PostApiWebhooksByIdReplayResponses, PostApiWebhooksByIdReplayErrors, GetApiWebhooksPendingRetriesData, GetApiWebhooksPendingRetriesResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiPayment = <ThrowOnError extends boolean = false>(options?: Options<GetApiPaymentData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiPaymentResponses, GetApiPaymentErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment',
        ...options
    });
};

export const postApiPayment = <ThrowOnError extends boolean = false>(options: Options<PostApiPaymentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostApiPaymentResponses, PostApiPaymentErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const deleteApiPaymentByPaymentId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiPaymentByPaymentIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteApiPaymentByPaymentIdResponses, DeleteApiPaymentByPaymentIdErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment/{paymentId}',
        ...options
    });
};

export const getApiPaymentByPaymentId = <ThrowOnError extends boolean = false>(options: Options<GetApiPaymentByPaymentIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetApiPaymentByPaymentIdResponses, GetApiPaymentByPaymentIdErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment/{paymentId}',
        ...options
    });
};

export const postApiPaymentByPaymentIdRefund = <ThrowOnError extends boolean = false>(options: Options<PostApiPaymentByPaymentIdRefundData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostApiPaymentByPaymentIdRefundResponses, PostApiPaymentByPaymentIdRefundErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment/{paymentId}/refund',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getApiPaymentHealth = <ThrowOnError extends boolean = false>(options?: Options<GetApiPaymentHealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiPaymentHealthResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment/health',
        ...options
    });
};

export const getApiPaymentProviders = <ThrowOnError extends boolean = false>(options?: Options<GetApiPaymentProvidersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiPaymentProvidersResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment/providers',
        ...options
    });
};

export const getApiPaymentProvidersByProviderHealth = <ThrowOnError extends boolean = false>(options: Options<GetApiPaymentProvidersByProviderHealthData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetApiPaymentProvidersByProviderHealthResponses, GetApiPaymentProvidersByProviderHealthErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment/providers/{provider}/health',
        ...options
    });
};

export const getApiKeys = <ThrowOnError extends boolean = false>(options?: Options<GetApiKeysData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiKeysResponses, GetApiKeysErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/keys',
        ...options
    });
};

export const postApiKeysGenerate = <ThrowOnError extends boolean = false>(options?: Options<PostApiKeysGenerateData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostApiKeysGenerateResponses, PostApiKeysGenerateErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/keys/generate',
        ...options
    });
};

export const postApiKeysRotate = <ThrowOnError extends boolean = false>(options: Options<PostApiKeysRotateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostApiKeysRotateResponses, PostApiKeysRotateErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/keys/rotate',
        ...options
    });
};

export const deleteApiKeysRevoke = <ThrowOnError extends boolean = false>(options: Options<DeleteApiKeysRevokeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteApiKeysRevokeResponses, DeleteApiKeysRevokeErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/keys/revoke',
        ...options
    });
};

export const getApiWebhooks = <ThrowOnError extends boolean = false>(options?: Options<GetApiWebhooksData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiWebhooksResponses, GetApiWebhooksErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/webhooks',
        ...options
    });
};

export const postApiWebhooksOrange = <ThrowOnError extends boolean = false>(options: Options<PostApiWebhooksOrangeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostApiWebhooksOrangeResponses, PostApiWebhooksOrangeErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/webhooks/orange',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const postApiWebhooksByIdReplay = <ThrowOnError extends boolean = false>(options: Options<PostApiWebhooksByIdReplayData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostApiWebhooksByIdReplayResponses, PostApiWebhooksByIdReplayErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/webhooks/{id}/replay',
        ...options
    });
};

export const getApiWebhooksPendingRetries = <ThrowOnError extends boolean = false>(options?: Options<GetApiWebhooksPendingRetriesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiWebhooksPendingRetriesResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/webhooks/pending-retries',
        ...options
    });
};