// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetApiPaymentData, GetApiPaymentResponses, PostApiPaymentData, PostApiPaymentResponses, DeleteApiPaymentByPaymentIdData, DeleteApiPaymentByPaymentIdResponses, GetApiPaymentByPaymentIdData, GetApiPaymentByPaymentIdResponses, PostApiPaymentByPaymentIdRefundData, PostApiPaymentByPaymentIdRefundResponses, GetApiPaymentHealthData, GetApiPaymentHealthResponses, GetApiPaymentProvidersByProviderHealthData, GetApiPaymentProvidersByProviderHealthResponses, GetApiWebhooksData, GetApiWebhooksResponses, PostApiWebhooksByIdReplayData, PostApiWebhooksByIdReplayResponses, PostApiWebhooksByIdReplayErrors, GetApiWebhooksPendingRetriesData, GetApiWebhooksPendingRetriesResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiPayment = <ThrowOnError extends boolean = false>(options?: Options<GetApiPaymentData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiPaymentResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment',
        ...options
    });
};

export const postApiPayment = <ThrowOnError extends boolean = false>(options?: Options<PostApiPaymentData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<PostApiPaymentResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

export const deleteApiPaymentByPaymentId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiPaymentByPaymentIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<DeleteApiPaymentByPaymentIdResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment/{paymentId}',
        ...options
    });
};

export const getApiPaymentByPaymentId = <ThrowOnError extends boolean = false>(options: Options<GetApiPaymentByPaymentIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetApiPaymentByPaymentIdResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment/{paymentId}',
        ...options
    });
};

export const postApiPaymentByPaymentIdRefund = <ThrowOnError extends boolean = false>(options: Options<PostApiPaymentByPaymentIdRefundData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostApiPaymentByPaymentIdRefundResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment/{paymentId}/refund',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getApiPaymentHealth = <ThrowOnError extends boolean = false>(options?: Options<GetApiPaymentHealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiPaymentHealthResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment/health',
        ...options
    });
};

export const getApiPaymentProvidersByProviderHealth = <ThrowOnError extends boolean = false>(options: Options<GetApiPaymentProvidersByProviderHealthData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetApiPaymentProvidersByProviderHealthResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/Payment/providers/{provider}/health',
        ...options
    });
};

export const getApiWebhooks = <ThrowOnError extends boolean = false>(options?: Options<GetApiWebhooksData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiWebhooksResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/webhooks',
        ...options
    });
};

export const postApiWebhooksByIdReplay = <ThrowOnError extends boolean = false>(options: Options<PostApiWebhooksByIdReplayData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostApiWebhooksByIdReplayResponses, PostApiWebhooksByIdReplayErrors, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/webhooks/{id}/replay',
        ...options
    });
};

export const getApiWebhooksPendingRetries = <ThrowOnError extends boolean = false>(options?: Options<GetApiWebhooksPendingRetriesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetApiWebhooksPendingRetriesResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'X-Api-Key',
                type: 'apiKey'
            }
        ],
        url: '/api/webhooks/pending-retries',
        ...options
    });
};