// This file is auto-generated by @hey-api/openapi-ts

export type ApiErrorResponse = {
    code: string;
    message: string;
    status: number;
    traceId?: string | null;
    timestampUtc: string;
    details?: {
        [key: string]: unknown;
    } | null;
};

export type CustomerInfo = {
    phoneNumber: string;
    email?: string | null;
    name?: string | null;
};

export type MerchantInfo = {
    reference: string;
    callbackUrl?: string | null;
    name?: string | null;
};

export type EscrowOptions = {
    enabled?: boolean;
    releaseMode?: string;
    autoTimeoutDays?: number | null;
};

export type PaymentRequest = {
    amount: number;
    currency: string;
    provider: 'MTN' | 'ORANGE' | 'MOOV' | 'WAVE' | 'AIRTEL';
    customer: CustomerInfo;
    merchant: MerchantInfo;
    description?: string | null;
    metadata?: {
        [key: string]: unknown;
    } | null;
    merchantApiKey?: string | null;
    escrow?: EscrowOptions;
    countryCode?: string;
};

export type EscrowInfo = {
    escrowId?: string;
    status?: string;
    releaseMode?: string;
    pickupCode?: string | null;
    autoReleaseAt?: string | null;
};

export type PaymentResponse = {
    transactionId: string;
    status: string;
    provider: string;
    providerReference?: string | null;
    amount?: number;
    currency: string;
    createdAt?: string;
    expiresAt?: string | null;
    paymentUrl?: string | null;
    escrow?: EscrowInfo;
    additionalData?: {
        [key: string]: unknown;
    } | null;
};

export type PaymentStatusResponse = {
    transactionId: string;
    status: string;
    provider: string;
    providerReference?: string | null;
    amount?: number;
    currency: string;
    createdAt?: string;
    completedAt?: string | null;
    failureReason?: string | null;
    additionalData?: {
        [key: string]: unknown;
    } | null;
};

export type RefundRequest = {
    amount?: number;
    reason?: string | null;
    idempotencyKey?: string | null;
    metadata?: {
        [key: string]: unknown;
    } | null;
};

export type RefundResponse = {
    refundId: string;
    transactionId: string;
    status: string;
    amount?: number;
    createdAt?: string;
};

export type TransactionSummary = {
    transactionRef: string;
    amount?: number;
    currency: string;
    status: string;
    provider: string;
    customerPhone?: string | null;
    customerName?: string | null;
    merchantRef?: string | null;
    createdAt?: string;
    completedAt?: string | null;
};

export type PagedTransactionSummary = {
    data: Array<TransactionSummary>;
    page: number;
    pageSize: number;
    totalCount: number;
    totalPages: number;
    hasNextPage: boolean;
    hasPreviousPage: boolean;
};

export type PaymentCancellationResponse = {
    paymentId: string;
    previousStatus: string;
    status: string;
    cancelledAt: string;
};

export type ProviderHealthResponse = {
    provider: string;
    status: string;
    timestamp: string;
};

export type ProviderSummaryResponse = {
    name: string;
    supportedFeatures: Array<string>;
};

export type ProviderListResponse = {
    count: number;
    items: Array<ProviderSummaryResponse>;
};

export type ServiceHealthResponse = {
    status: string;
    service: string;
    version: string;
    timestamp: string;
};

export type ApiKeyInfo = {
    merchantId?: string | null;
    merchantName?: string | null;
    key: string;
    mode: 'test' | 'live';
    createdAt?: string | null;
};

export type ApiKeyListResponse = {
    keys: Array<ApiKeyInfo>;
};

export type ApiKeyOperationResponse = {
    apiKey: string;
    mode: 'test' | 'live';
    createdAt: string;
};

export type ApiKeyRevokeResponse = {
    revoked: boolean;
    message: string;
};

export type WebhookSummary = {
    id: string;
    eventType: string;
    status: string;
    retryCount: number;
    createdAt: string;
    deliveredAt?: string | null;
    nextRetryAt?: string | null;
    lastError?: string | null;
    lastHttpStatusCode?: number | null;
};

export type WebhookListResponse = {
    items: Array<WebhookSummary>;
    page: number;
    pageSize: number;
};

export type WebhookReplayResponse = {
    success: boolean;
    httpStatusCode: number;
    errorMessage?: string | null;
    durationMs: number;
};

export type PendingWebhookRetriesResponse = {
    count: number;
    items: Array<WebhookSummary>;
};

export type OrangeWebhookPayload = {
    orderId?: string | null;
    payToken?: string | null;
    status?: string | null;
    message?: string | null;
    txnId?: string | null;
    subscriberMsisdn?: string | null;
    amount?: string | null;
};

export type GetApiPaymentData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        status?: string;
        provider?: string;
        currency?: string;
        from?: string;
        to?: string;
        search?: string;
    };
    url: '/api/Payment';
};

export type GetApiPaymentErrors = {
    /**
     * Server error
     */
    500: ApiErrorResponse;
};

export type GetApiPaymentError = GetApiPaymentErrors[keyof GetApiPaymentErrors];

export type GetApiPaymentResponses = {
    /**
     * Paginated list of merchant payments
     */
    200: PagedTransactionSummary;
};

export type GetApiPaymentResponse = GetApiPaymentResponses[keyof GetApiPaymentResponses];

export type PostApiPaymentData = {
    body: PaymentRequest;
    path?: never;
    query?: never;
    url: '/api/Payment';
};

export type PostApiPaymentErrors = {
    /**
     * Validation or business error
     */
    400: ApiErrorResponse;
    /**
     * Server error
     */
    500: ApiErrorResponse;
};

export type PostApiPaymentError = PostApiPaymentErrors[keyof PostApiPaymentErrors];

export type PostApiPaymentResponses = {
    /**
     * Payment created
     */
    201: PaymentResponse;
};

export type PostApiPaymentResponse = PostApiPaymentResponses[keyof PostApiPaymentResponses];

export type DeleteApiPaymentByPaymentIdData = {
    body?: never;
    path: {
        paymentId: string;
    };
    query?: never;
    url: '/api/Payment/{paymentId}';
};

export type DeleteApiPaymentByPaymentIdErrors = {
    /**
     * Cancellation not allowed
     */
    400: ApiErrorResponse;
    /**
     * Ownership denied
     */
    403: ApiErrorResponse;
    /**
     * Payment not found
     */
    404: ApiErrorResponse;
    /**
     * Server error
     */
    500: ApiErrorResponse;
};

export type DeleteApiPaymentByPaymentIdError = DeleteApiPaymentByPaymentIdErrors[keyof DeleteApiPaymentByPaymentIdErrors];

export type DeleteApiPaymentByPaymentIdResponses = {
    /**
     * Payment cancelled
     */
    200: PaymentCancellationResponse;
};

export type DeleteApiPaymentByPaymentIdResponse = DeleteApiPaymentByPaymentIdResponses[keyof DeleteApiPaymentByPaymentIdResponses];

export type GetApiPaymentByPaymentIdData = {
    body?: never;
    path: {
        paymentId: string;
    };
    query?: never;
    url: '/api/Payment/{paymentId}';
};

export type GetApiPaymentByPaymentIdErrors = {
    /**
     * Ownership denied
     */
    403: ApiErrorResponse;
    /**
     * Payment not found
     */
    404: ApiErrorResponse;
    /**
     * Server error
     */
    500: ApiErrorResponse;
};

export type GetApiPaymentByPaymentIdError = GetApiPaymentByPaymentIdErrors[keyof GetApiPaymentByPaymentIdErrors];

export type GetApiPaymentByPaymentIdResponses = {
    /**
     * Payment status
     */
    200: PaymentStatusResponse;
};

export type GetApiPaymentByPaymentIdResponse = GetApiPaymentByPaymentIdResponses[keyof GetApiPaymentByPaymentIdResponses];

export type PostApiPaymentByPaymentIdRefundData = {
    body: RefundRequest;
    path: {
        paymentId: string;
    };
    query?: never;
    url: '/api/Payment/{paymentId}/refund';
};

export type PostApiPaymentByPaymentIdRefundErrors = {
    /**
     * Refund validation error
     */
    400: ApiErrorResponse;
    /**
     * Ownership denied
     */
    403: ApiErrorResponse;
    /**
     * Payment not found
     */
    404: ApiErrorResponse;
    /**
     * Server error
     */
    500: ApiErrorResponse;
};

export type PostApiPaymentByPaymentIdRefundError = PostApiPaymentByPaymentIdRefundErrors[keyof PostApiPaymentByPaymentIdRefundErrors];

export type PostApiPaymentByPaymentIdRefundResponses = {
    /**
     * Refund created
     */
    201: RefundResponse;
};

export type PostApiPaymentByPaymentIdRefundResponse = PostApiPaymentByPaymentIdRefundResponses[keyof PostApiPaymentByPaymentIdRefundResponses];

export type GetApiPaymentHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Payment/health';
};

export type GetApiPaymentHealthResponses = {
    /**
     * Service health
     */
    200: ServiceHealthResponse;
};

export type GetApiPaymentHealthResponse = GetApiPaymentHealthResponses[keyof GetApiPaymentHealthResponses];

export type GetApiPaymentProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Payment/providers';
};

export type GetApiPaymentProvidersResponses = {
    /**
     * Enabled providers
     */
    200: ProviderListResponse;
};

export type GetApiPaymentProvidersResponse = GetApiPaymentProvidersResponses[keyof GetApiPaymentProvidersResponses];

export type GetApiPaymentProvidersByProviderHealthData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: never;
    url: '/api/Payment/providers/{provider}/health';
};

export type GetApiPaymentProvidersByProviderHealthErrors = {
    /**
     * Provider not supported
     */
    404: ApiErrorResponse;
    /**
     * Server error
     */
    500: ApiErrorResponse;
};

export type GetApiPaymentProvidersByProviderHealthError = GetApiPaymentProvidersByProviderHealthErrors[keyof GetApiPaymentProvidersByProviderHealthErrors];

export type GetApiPaymentProvidersByProviderHealthResponses = {
    /**
     * Provider health
     */
    200: ProviderHealthResponse;
};

export type GetApiPaymentProvidersByProviderHealthResponse = GetApiPaymentProvidersByProviderHealthResponses[keyof GetApiPaymentProvidersByProviderHealthResponses];

export type GetApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/keys';
};

export type GetApiKeysErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Server error
     */
    500: ApiErrorResponse;
};

export type GetApiKeysError = GetApiKeysErrors[keyof GetApiKeysErrors];

export type GetApiKeysResponses = {
    /**
     * Active API keys
     */
    200: ApiKeyListResponse;
};

export type GetApiKeysResponse = GetApiKeysResponses[keyof GetApiKeysResponses];

export type PostApiKeysGenerateData = {
    body?: never;
    path?: never;
    query?: {
        isTestMode?: boolean;
    };
    url: '/api/keys/generate';
};

export type PostApiKeysGenerateErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Merchant not found
     */
    404: ApiErrorResponse;
    /**
     * Server error
     */
    500: ApiErrorResponse;
};

export type PostApiKeysGenerateError = PostApiKeysGenerateErrors[keyof PostApiKeysGenerateErrors];

export type PostApiKeysGenerateResponses = {
    /**
     * API key generated
     */
    201: ApiKeyOperationResponse;
};

export type PostApiKeysGenerateResponse = PostApiKeysGenerateResponses[keyof PostApiKeysGenerateResponses];

export type PostApiKeysRotateData = {
    body?: never;
    path?: never;
    query: {
        currentApiKey: string;
        isTestMode?: boolean;
    };
    url: '/api/keys/rotate';
};

export type PostApiKeysRotateErrors = {
    /**
     * Invalid request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Merchant not found
     */
    404: ApiErrorResponse;
    /**
     * Server error
     */
    500: ApiErrorResponse;
};

export type PostApiKeysRotateError = PostApiKeysRotateErrors[keyof PostApiKeysRotateErrors];

export type PostApiKeysRotateResponses = {
    /**
     * API key rotated
     */
    200: ApiKeyOperationResponse;
};

export type PostApiKeysRotateResponse = PostApiKeysRotateResponses[keyof PostApiKeysRotateResponses];

export type DeleteApiKeysRevokeData = {
    body?: never;
    path?: never;
    query: {
        apiKey: string;
    };
    url: '/api/keys/revoke';
};

export type DeleteApiKeysRevokeErrors = {
    /**
     * Invalid request
     */
    400: ApiErrorResponse;
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
    /**
     * Server error
     */
    500: ApiErrorResponse;
};

export type DeleteApiKeysRevokeError = DeleteApiKeysRevokeErrors[keyof DeleteApiKeysRevokeErrors];

export type DeleteApiKeysRevokeResponses = {
    /**
     * API key revoked
     */
    200: ApiKeyRevokeResponse;
};

export type DeleteApiKeysRevokeResponse = DeleteApiKeysRevokeResponses[keyof DeleteApiKeysRevokeResponses];

export type GetApiWebhooksData = {
    body?: never;
    path?: never;
    query?: {
        merchantId?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/webhooks';
};

export type GetApiWebhooksErrors = {
    /**
     * Unauthorized
     */
    401: ApiErrorResponse;
};

export type GetApiWebhooksError = GetApiWebhooksErrors[keyof GetApiWebhooksErrors];

export type GetApiWebhooksResponses = {
    /**
     * Webhook history
     */
    200: WebhookListResponse;
};

export type GetApiWebhooksResponse = GetApiWebhooksResponses[keyof GetApiWebhooksResponses];

export type PostApiWebhooksOrangeData = {
    body: OrangeWebhookPayload;
    path?: never;
    query?: never;
    url: '/api/webhooks/orange';
};

export type PostApiWebhooksOrangeErrors = {
    /**
     * Incomplete payload
     */
    400: unknown;
};

export type PostApiWebhooksOrangeResponses = {
    /**
     * Orange webhook acknowledged
     */
    200: {
        received?: boolean;
        error?: string | null;
    };
};

export type PostApiWebhooksOrangeResponse = PostApiWebhooksOrangeResponses[keyof PostApiWebhooksOrangeResponses];

export type PostApiWebhooksByIdReplayData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/webhooks/{id}/replay';
};

export type PostApiWebhooksByIdReplayErrors = {
    /**
     * Webhook not found
     */
    404: ApiErrorResponse;
};

export type PostApiWebhooksByIdReplayError = PostApiWebhooksByIdReplayErrors[keyof PostApiWebhooksByIdReplayErrors];

export type PostApiWebhooksByIdReplayResponses = {
    /**
     * Replay result
     */
    200: WebhookReplayResponse;
};

export type PostApiWebhooksByIdReplayResponse = PostApiWebhooksByIdReplayResponses[keyof PostApiWebhooksByIdReplayResponses];

export type GetApiWebhooksPendingRetriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/webhooks/pending-retries';
};

export type GetApiWebhooksPendingRetriesResponses = {
    /**
     * Pending retries
     */
    200: PendingWebhookRetriesResponse;
};

export type GetApiWebhooksPendingRetriesResponse = GetApiWebhooksPendingRetriesResponses[keyof GetApiWebhooksPendingRetriesResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};