// This file is auto-generated by @hey-api/openapi-ts

export type CustomerInfo = {
    phoneNumber: string;
    email?: string | null;
    name?: string | null;
};

export type MerchantInfo = {
    reference: string;
    callbackUrl?: string | null;
    name?: string | null;
};

export type PaymentRequest = {
    amount: number;
    currency: string;
    provider: string;
    customer: CustomerInfo;
    merchant: MerchantInfo;
    description?: string | null;
    metadata?: {
        [key: string]: unknown;
    } | null;
    merchantApiKey?: string | null;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | undefined;
};

export type RefundRequest = {
    amount?: number;
    reason?: string | null;
    metadata?: {
        [key: string]: unknown;
    } | null;
};

export type WebhookListResponse = {
    items?: Array<WebhookSummary> | null;
    page?: number;
    pageSize?: number;
};

export type WebhookReplayResponse = {
    success?: boolean;
    httpStatusCode?: number;
    errorMessage?: string | null;
    durationMs?: number;
};

export type WebhookSummary = {
    id?: string;
    eventType?: string | null;
    status?: string | null;
    retryCount?: number;
    createdAt?: string;
    deliveredAt?: string | null;
    nextRetryAt?: string | null;
    lastError?: string | null;
    lastHttpStatusCode?: number | null;
};

export type GetApiPaymentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Payment';
};

export type GetApiPaymentResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiPaymentData = {
    body?: PaymentRequest;
    path?: never;
    query?: never;
    url: '/api/Payment';
};

export type PostApiPaymentResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type DeleteApiPaymentByPaymentIdData = {
    body?: never;
    path: {
        paymentId: string;
    };
    query?: never;
    url: '/api/Payment/{paymentId}';
};

export type DeleteApiPaymentByPaymentIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiPaymentByPaymentIdData = {
    body?: never;
    path: {
        paymentId: string;
    };
    query?: never;
    url: '/api/Payment/{paymentId}';
};

export type GetApiPaymentByPaymentIdResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type PostApiPaymentByPaymentIdRefundData = {
    body?: RefundRequest;
    path: {
        paymentId: string;
    };
    query?: never;
    url: '/api/Payment/{paymentId}/refund';
};

export type PostApiPaymentByPaymentIdRefundResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiPaymentHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Payment/health';
};

export type GetApiPaymentHealthResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiPaymentProvidersByProviderHealthData = {
    body?: never;
    path: {
        provider: string;
    };
    query?: never;
    url: '/api/Payment/providers/{provider}/health';
};

export type GetApiPaymentProvidersByProviderHealthResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type GetApiWebhooksData = {
    body?: never;
    path?: never;
    query?: {
        merchantId?: string;
        page?: number;
        pageSize?: number;
    };
    url: '/api/webhooks';
};

export type GetApiWebhooksResponses = {
    /**
     * Success
     */
    200: WebhookListResponse;
};

export type GetApiWebhooksResponse = GetApiWebhooksResponses[keyof GetApiWebhooksResponses];

export type PostApiWebhooksByIdReplayData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/webhooks/{id}/replay';
};

export type PostApiWebhooksByIdReplayErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostApiWebhooksByIdReplayError = PostApiWebhooksByIdReplayErrors[keyof PostApiWebhooksByIdReplayErrors];

export type PostApiWebhooksByIdReplayResponses = {
    /**
     * Success
     */
    200: WebhookReplayResponse;
};

export type PostApiWebhooksByIdReplayResponse = PostApiWebhooksByIdReplayResponses[keyof PostApiWebhooksByIdReplayResponses];

export type GetApiWebhooksPendingRetriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/webhooks/pending-retries';
};

export type GetApiWebhooksPendingRetriesResponses = {
    /**
     * Success
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};